language: ruby

rvm:
  - 3.0.1

dist: focal

script:
  - bundle exec rails webpacker:instal
  - bundle update --bundler
  - bundle exec rake db:migrate
  - bundle exec rspec spec
  - bundle exec cucumber

branches:
  only:
    - main
