name: Build rails app

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [3.0.1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          bundler-cache: true

      - run: yarn add @rails/webpacker
      - run: bundle update --bundler
      - run: RAILS_ENV=test bundle exec rails webpacker:compile
      - run: bundle exec rake db:migrate
      - run: bundle exec rspec spec
      - run: bundle exec cucumber
