name: Build rails app

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fazendo checkout
        uses: actions/checkout@v2

      - name: Instalando Ruby
        shell: bash {0}
        run: |
          gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          curl -sSL https://get.rvm.io | bash
          source /home/runner/.rvm/scripts/rvm
          rvm install 3.0.1
          rvm use 3.0.1 -- default

      - name: Instalando Webpacker e Bundler
        shell: bash {0}
        run: |
          source /home/runner/.rvm/scripts/rvm
          yarn add @rails/webpacker
          bundle update --bundler
          RAILS_ENV=test bundle exec rails webpacker:compile

      - name: Configurando banco de dados
        shell: bash {0}
        run: |
          source /home/runner/.rvm/scripts/rvm
          RAILS_ENV=test bundle exec rake db:migrate

      - name: Executando testes de integração (Cucumber)
        shell: bash {0}
        run: |
          source /home/runner/.rvm/scripts/rvm
          bundle exec cucumber

      - name: Executando testes de unidade (RSpec)
        shell: bash {0}
        run: |
          source /home/runner/.rvm/scripts/rvm
          bundle exec rspec spec
